### PR TITLE
ED-2086: OCI support for Deploy/Lern/LernFlinkJobs

### PR DESCRIPTION
**Pull request by ddevadat**
Added OCI support for  Deploy/Lern/LernFlinkJobs

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Hari-stackroute — CHANGES_REQUESTED** [review]
This pr contains changes of optional-nodes relates code which is done as a part of release-5.1.0 but base branch is showing release-5.0.2 and that too it doesn't contain updated version of release-5.1.0. 
Please either drop those changes or update correctly.

**Comment by ddevadat** [comment]
> This pr contains changes of optional-nodes relates code which is done as a part of release-5.1.0 but base branch is showing release-5.0.2 and that too it doesn't contain updated version of release-5.1.0. Please either drop those changes or update correctly.

The changes in the PR were done on top of release-5.1.0.
Are you suggesting that the PR should be merged to upstream branch release-5.1.0 instead of release-5.0.2?

**Comment by AmiableAnil** [comment]
@ddevadat Please update the image in circleci from `circleci/openjdk:stretch` to `cimg/openjdk:11.0.19`. To successfully run the circleci.

**Comment by AmiableAnil** [comment]
> > This pr contains changes of optional-nodes relates code which is done as a part of release-5.1.0 but base branch is showing release-5.0.2 and that too it doesn't contain updated version of release-5.1.0. Please either drop those changes or update correctly.
> 
> The changes in the PR were done on top of release-5.1.0. Are you suggesting that the PR should be merged to upstream branch release-5.1.0 instead of release-5.0.2?

Uf the changes are done on release-5.1.0 than upstream should be release-5.1.0 only.

**Comment by ddevadat** [comment]
Raised PR https://github.com/Sunbird-Lern/data-pipeline/pull/143 towards release-5.1.0

**Comment by ddevadat** [comment]
Closed in favour of PR https://github.com/Sunbird-Lern/data-pipeline/pull/143

**Pull request closed without merging**
